### ISSUE TITLE
Can we make it sleep?

### ISSUE THREAD

**Issue by the-butterfry** [dimhoff/ESP32-CAM_Interval#1]
I got a last minute idea for a hike I'm going on this coming weekend.
I have one of these ESP32-Cams and a cute little solar powered battery setup that is perfect for it. The place I'm going hiking is somewhere we go back to every year, and I was thinking of throwing up the camera and just let it sit for a year taking photos once every hour or so. 

Think we can make it deep sleep and timer wakeup every x minutes, do a loop and take a photo and go back to sleep?

**Comment by dimhoff** [comment]
Yes, that was on the TODO list.

I just did some experiments trying to get light-sleep to work, see the light-sleep branch. But it crashes for unknown reasons after 2 pictures. It's all a bit tricky since I don't know how the sleep function messes up the initialization of the camera and SD drivers.

If I have some more time I look into this.

**Comment by dimhoff** [comment]
The light sleep issues are due to the camera driver.

Wrote a new sleep implementation using deep sleep. This only works for longer intervals between captures, > 10sec. Once an hour should be okay. It is now available on master(6795dbd8d2a3a11cf1a3c045c6f50755d85661f6).

I must warn tho that this firmware was born a couple of days ago. So don't expect it to be production ready or well tested. I have low expectations of it running flawlessly for a year without maintenance.

In your case I suggest disabling Wi-Fi and GNSS in config.h when building. This saves boot time and energy.

Also are you able to get any decent quality images from your ESP32-CAM of a landscape? mine seem to have a fixed focus of about 1 meter away. Things further away are rather vague.

**Comment by the-butterfry** [comment]
I noticed you just started this thing out. My browsing around turned up a bunch of issues with resuming from sleep conflicting with the LED pin and others. I'll give it a go this afternoon and see what we can come up with. 

I think you may have a misaligned camera. I don't have any issues with focus at mid-distance.

**Comment by the-butterfry** [comment]
How does the interval and the sleep interplay here? I haven't gone through the code yet to see how you're sleeping and setting sleep, or if picture taking is a wake event.  Do I need to set interval as X and Sleep as X - 5seconds or something reasonable so that it wakes up just before the picture time?

Or is taking a picture a wake event so we only need to set the photo as 1 hr. or whatever greater than 10sec.

**Comment by dimhoff** [comment]
Just set the interval in the configuration file(=/camera.cfg) to '3600000'. The firmware will automatically go to sleep if the interval is big enough.

**Comment by the-butterfry** [comment]
great!

EDIT: Wait, there's something dodgy with this reader. Sometimes I put the card in and it won't even recognize it, others it does, but can't read.. and lastly sometimes it totally works and writes readable files.. oh boy. LOL well worst case is it sits there a year and doesn't do anything...

I'll send some pics of the project finalized and then installed out in the woods if I can get it all together in time

So I got it loaded up but apparently there's something wonky here. Here's a serial debug from boot:


rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:928
ho 0 tail 12 room 4
load:0x40078000,len:8424
ho 0 tail 12 room 4
load:0x40080400,len:5868
entry 0x4008069c
�
Mounting SD card... Done
E (2495) sdmmc_req: sdmmc_host_wait_for_event returned 0x107
E (2496) sdmmc_cmd: sdmmc_read_sectors_dma: sdmmc_send_cmd returned 0x107
E (2496) diskio_sdmmc: sdmmc_read_blocks failed (263)
No config found, using defaults.
Failed to determine current date/time

E (3508) sdmmc_req: sdmmc_host_wait_for_event returned 0x107
E (3508) sdmmc_cmd: sdmmc_read_sectors_dma: sdmmc_send_cmd returned 0x107
E (3509) diskio_sdmmc: sdmmc_read_blocks failed (263)
Error reading directory /sdcard/

I've got camera.cfg in root of a fat32 4gb card. Seems to be mounting? I've got wifi and gnss //'d out in the config.h

**Comment by dimhoff** [comment]
You can try enabling WITH_SD_4BIT in config.h. else try a different SD card.

**Comment by dimhoff** [comment]
I did some power usage measurements. And the board still uses ~4mA @ 3.3V when in deep sleep (that is after commit c65ed3d3b02fac87e127f52215c2412c1f388618). This is almost all used by the camera module. At least removing the camera while in deep sleep reduces power consumption to about 0.4 mA.

**Comment by the-butterfry** [comment]
Interesting.. my tests show in the neighborhood of 25mA in deep sleep with a peak at about 160mA at photo time.
I'll flash up c65ed3d and test again.

**Comment by dimhoff** [comment]
Do you measure at the 5 Volt? I removed the regulator and measure directly at the 3v3.

**Comment by the-butterfry** [comment]
Measuring at the 5v off of USB since that will be real life usage when it's all complete and drawing off of the solar charger/battery.

New readings are 12mA Sleep and climbs to max of ~160mA for a second when active as the wake processes happens.

I switched SD cards and it works better, but so far I can get about 5 sleep cycles out of it before it locks up at: 
Next image at: Thu Jan  1 00:05:38 1970
E (3483) sdmmc_req: sdmmc_host_wait_for_event returned 0x107
E (3483) sdmmc_cmd: sdmmc_read_sectors_dma: sdmmc_send_cmd returned 0x107
E (3484) diskio_sdmmc: sdmmc_read_blocks failed (263)
Error reading directory /sdcard/

I'll try the WITH_SD_4BIT

**Comment by the-butterfry** [comment]
the WITH_SD_4BIT produces the flash constantly on at low when sleeping.
Also I've got the Flash set to off in the .cfg ( enable_flash = false ) and the flash still fires on photo. The SD seems more reliable now though..

Here's the serial dump of the config I have set
Mounting SD card... Done
Loading config... 
 - 'interval' => '50000'
 - 'ssid' => ''
 - 'password' => ''
 - 'ntp_server' => 'pool.ntp.org'
 - 'timezone' => 'GMT0'
 - 'enable_busy_led' => 'true'
 - 'enable_flash' => 'false'
 - 'rotation' => '0'
 - 'framesize' => '1600x1200'
 - 'quality' => '10'
 - 'contrast' => '0'
 - 'brightness' => '0'
 - 'saturation' => '0'
 - 'colorbar' => 'false'
 - 'hmirror' => 'false'
 - 'vflip' => 'false'
 - 'awb' => 'true'
 - 'awb_gain' => 'true'
 - 'wb_mode' => 'auto'
 - 'agc' => 'true'
 - 'agc_gain' => '1'
 - 'gainceiling' => '2'
 - 'aec' => 'true'
 - 'aec2' => 'true'
 - 'aec_value' => '51'
 - 'ae_level' => '0'
 - 'dcw' => 'true'
 - 'bpc' => 'false'
 - 'wpc' => 'true'
 - 'raw_gma' => 'true'
 - 'lenc' => 'true'
 - 'special_effect' => 'none'
Config loaded.

**Comment by dimhoff** [comment]
Yes, the flash will light up when using 4-bit SD Card communication. That's because the flash led is connected to one of the data lines of the SD card. That is the reason that by default 1-bit SD card communication is used. Only way to disable flash LED with 4-bit SD card communication is to cut the trace to the LED, as described in this video https://www.youtube.com/watch?v=1ojUXSgMBVY

**Comment by the-butterfry** [comment]
Since this thing is going to be installed out in nature, near other campers I probably don't want a flash going off once an hour.... I'll look into it

**Comment by the-butterfry** [comment]
There seems to be a magic sequence to make everything happy. If I eject the card, hit reset and push it back in right away things seem to work. I'm going to leave it at that.
Before it gets installed in a tree, I'll leave it running for a few hours to make sure everything is as it should be. I've settled on a photo every 30 minutes, mostly because i'm not able to bring a laptop to modify the cfg file. Waiting an hour between photos to test it seems a bit much. I've got plenty of SD card space... and hopefully enough power over time. 

My math works like this: 6000mAh battery. 
A way over estimated average of a constant 20mAh draw. (It's probably more like 15 with booting up 2x an hour for 5 seconds from a 10-12mAh sleep draw) = around 12-14 days of battery power
The solar panel in full sun can provide ~3-400mAh of power. So even if I get just a few hours a sun a week this should be plenty to keep it going indefinitely. 

Here's the real problem.. if it ever runs out of power and dies, then reboots the device probably won't ever come back up. I'm relying on the draw being small enough that there is always enough power left in it to do the task and keep it sleeping.

I'll send pix of it installed and running.

**Comment by dimhoff** [comment]
Cool, I'd love to see some images!

**Comment by the-butterfry** [comment]
So I completely failed to bring my phone to take photos of us installing LOL.. the install area was too far away to go back and
 get it. I did though get a photo from the other side of the lake.  I'll have to take some photos next year when I go to get it 
![20190819_180312162_iOS](https://user-images.githubusercontent.com/37050797/63471122-37c3f780-c423-11e9-8e72-6a3dac9c65de.jpg) The camera is installed on the other side of the lake. its in the first tree that the bleached white log is pointed at.
![20190816_032214068_iOS](https://user-images.githubusercontent.com/37050797/63471228-6c37b380-c423-11e9-9172-71c2edc14206.jpg)
![20190816_032200130_iOS](https://user-images.githubusercontent.com/37050797/63471234-6fcb3a80-c423-11e9-87a6-121b6e76507c.jpg)

**Comment by dimhoff** [comment]
Thanks for the images. Certainly a nice place to make a time-lapse.
